### ISSUE TITLE
Add Chakra Card Component

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#1024]
Now that we have upgraded our next/chakra/react we can add new chakra components.

This issue is to add Card, CardHeader, CardBody, CardFooter

https://chakra-ui.com/docs/components/card

**Comment by Pekka1721** [comment]
Hi Alek99,
Can you elobrate  the issue and what has to be done using chakar ui  ?

New bie questions

**Comment by Alek99** [comment]
Sure take a look at how some of our components are implemented such as box, flex, etc. The card component in chakra should follow a very similar pattern.

**Comment by Alek99** [comment]
We are creating a card component by wrapping the chakra card component as seen in the link. Lmk if you have any questions

**Comment by iron3oxide** [comment]
Working on it rn and having a medium sized meltdown because I want to implement a `create()` override as discussed in #980 so that only `CardHeader`, `CardBody` and `CardFooter` can be children of `Card` and only the props listed in the docs can be passed as the `props` argument. Much to my dismay, one can apparently provide any CSS keyword argument to `Card` and it is still expected to work. 

I think we need a data structure that encompasses every available CSS argument for the component in question and (if one is provided) maps it to the given value. Example:

```python
pc.input("Example", css=pc.CSS(align="center", filter="blur(1px)"))
```

The lazy alternative would be to let every component take an optional `css` dict, which would make some things easier but of course isn't as fool proof. I hope my problem is somewhat understandable

**Comment by iron3oxide** [comment]
I see, with some modification that could solve the "only header, body, footer should be children" problem. The "only valid arguments to the JS component should be allowed in the python component" problem remains (which is why I think something akin to `pc.CSS` is necessary), but since that's the case for every component as of now, I guess I'll have to live with that.

**Comment by Lendemor** [comment]
> "only valid arguments to the JS component should be allowed in the python component"

I don't see why that's a problem, it has not been a problem for any other of the ChakraUI component, what make this one different ?

**Comment by iron3oxide** [comment]
It's not a problem for this specific component (and thus I probably should have mentioned it elsewhere and will ignore it for the initial implementation), but a DX problem for every component in general (see reasoning in the issue mentioned above). IMHO programming errors should be eliminated where feasible (e.g. string enums instead of strings to prevent typos and other invalid input) or pop up as soon as possible, and that's usually in your editor.

Until trying to implement this component, I thought it was possible to achieve this by simply overriding the `create` method in each component and maybe adding some string enums to constrain to valid input. Now I know that every `create` method must be able to take a plethora of CSS keyword arguments, which explains the current design but was the source of my frustration and proposal.

**Comment by iron3oxide** [comment]
I have it working locally now, PR will hopefully follow soon. Just testing around a little, docs and tests are also not there yet.
