### ISSUE TITLE
Enhancement: Add IDE (VS code) code actions to wrap components

### ISSUE THREAD

**Issue by mister-rao** [pynecone-io/pynecone#1242]
In flutter framework we can wrap components together without manually having to find and add opening and closing brackets. I was thinking we could have a similar feature for pynecone as it makes it easy to modify the code. 

For example; lets say I have a pc.hstack and I want to wrap it with a pc.container, currently I'd have to find the ending brackets of the hstack and then add the closing bracket of the new container. This gets tedious when we have a lot of nested components.

**Comment by Alek99** [comment]
If your components get too long I would suggest breaking them up into separate functions. 

Pynecone is declarative instead of imperative, similar to web frameworks like react. I think the leads to cleaner more understandable code in the end, it's just a matter of breaking things up in to sub components when your components gets too long

**Comment by mister-rao** [comment]
fair enough. thanks for the quick reply.
