### ISSUE TITLE
Create Pynecone Docker Image

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#253]

**Comment by FHU-yezi** [comment]
If we use docker compose to deploy, maybe we can use Caddy and reverse proxy port 8080 `/event` to 443 `/event`, then we can only export one port 443 to public.

**Comment by matt-grain** [comment]
Something related, a command line to export the static web app on one site and to package the serverside separately would be great too.

**Comment by FHU-yezi** [comment]
> Something related, a command line to export the static web app on one site and to package the serverside separately would be great too.

Yes, we can get better performance by use Caddy to server static files and FastAPI to serve backend, with Caddy as a reverse proxy.

**Comment by hololeo** [comment]
i did a docker image of pynecone. it was done for my mac. its possibel to dev with it if you mount a volume on it and then bash into container and run pc init/run in the mounted directory.

it was purely for learning and investigating, i dont recommend it for real development as the real time reload feature makes very high CPU demands since i guess it has to cross layers

https://hub.docker.com/r/holocloud/pynecone

**Comment by SaarthakMaini** [comment]
Is this issue still open for contribution?
If yes, I would like to contribute to this issue
