### ISSUE TITLE
Websockets connection drops on Safari/iOS

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#258]
**Describe the bug**
The websocket connection is inconsistent on mobile sometimes for Safari/iOS.

**To Reproduce**
See related issue: https://github.com/HeinrichApfelmus/threepenny-gui/issues/130

**Expected behavior**
The connection should be resilient and reconnect when dropped.

**Comment by cie-tenebris** [comment]
I’m glad to finally see this issue here.

Any idea for when this will be included in a milestone? It’s seems to be a critical issue. 

From my experiments with the examples, most have these issues in Safari/iOS, including the docs site when it comes to the burger menu. It makes deploying reliable Pynecone apps for iOS devices pointless right now. They’re extremely unreliable. Same with browsers like FF right now which are more aggressive with websocket connections.

A large portion of the mobile market for Pynecone apps is inaccessible right now.
