### ISSUE TITLE
`pc run` emits error if a project named ‘test’

### ISSUE THREAD

**Issue by dev-onejun** [pynecone-io/pynecone#270]
## Describe the bug
`pc run` emits error if a project named ‘test’.

I found that the name `test` can conflict with another python modules.
But is it fine that pynecone cannot run with the name `test`?

## To Reproduce

``` bash
$ mkdir test; cd test;
$ pc init
$ pc run
```

## Expected behavior
running well

## Screenshots
![IMG_0650](https://user-images.githubusercontent.com/46886909/212770176-4761dde5-6521-49f7-ad73-be3604a8a673.jpeg)

## Specifics (please complete the following information):
 - Python Version: 3.10
 - Pynecone Version: 0.1.12
 - OS: Ubuntu 22.04.01
 - Browser (Optional):

**Comment by Alek99** [comment]
Got it thanks, seem like you can't have a pynecone project called `pynecone` or `test` we should make this clear or throw a better message

**Comment by Alek99** [comment]
Wait when I did this it seems to work fine, anyone else getting this issue?

**Comment by dev-onejun** [comment]
Hi, @Alek99.

At first, I’m little confused that the error is not occurred when I run the command on the same computer which the only difference was that it was only on docker environment.
I ran it on the image `python:3.10.6-buster`.

![IMG_0652](https://user-images.githubusercontent.com/46886909/212777644-c1803c46-0167-4c32-9a37-577c25e3b5fb.jpeg)

However, it still emits error on the image `ubuntu:jammy` which is the same OS as my computer.
I know that `buster` uses debian.

![IMG_0653](https://user-images.githubusercontent.com/46886909/212777662-ed7abefe-0333-40cc-b554-1b53af8204de.jpeg)

**Comment by picklelo** [comment]
Hmm the only thing I can think of is something in related to your `$PYTHONPATH`. The two reasons this may occur are:
* You module `test` is not in you `PYTHONPATH`, but it since you're running out from the same directory that shouldn't be the issue
* There exists some other module named `test` and the import is confusing it with your local folder.

In any case, maybe try renaming the project and see if you get the same issue on that Docker?

**Comment by FHU-yezi** [comment]
Just try to `import test` on my server which use Ubuntu 22.04, and it successed?

I think Ubuntu's build-in Python comes up with a package named test, when I try to `print(test.__path__)`, it gave me `/usr/lib/python3.10/test`, and this folder is exist, with some Python file in it.

So we can explain this problem. Docker Image of Python is build on Debian, and you use Ubuntu, Debian does not has this package but Ubuntu does.

For solution, we can't delete this package due to risk of break the system, just don't use this name with Ubuntu, at least use a Docker Image for deployment.

**Comment by Alek99** [comment]
> Just try to `import test` on my server which use Ubuntu 22.04, and it successed?
> 
> I think Ubuntu's build-in Python comes up with a package named test, when I try to `print(test.__path__)`, it gives me `/usr/lib/python3.10/test`, and this folder is exist, with some Python file in it.
> 
> So we can explain this problem. Docker Image of Python is build on Debian, and you use Ubuntu, Debian does not has this package but Ubuntu does.
> 
> For solution, we can't delete this package due to risk of break the system, just don't use this name with Ubuntu, at least use a Docker Image for deployment.

Oh nice I didn't know this change, thanks for finding this

**Comment by dev-onejun** [comment]
> ... when I try to `print(test.__path__)`, it gives me `/usr/lib/python3.10/test`, and this folder is exist, with some Python file in it.
> 
> So we can explain this problem. Docker Image of Python is build on Debian, and you use Ubuntu, Debian does not has this package but Ubuntu does.
> 
> For solution, we can't delete this package due to risk of break the system, just don't use this name with Ubuntu, at least use a Docker Image for deployment.

Right. And I checked that it occurs in Ubuntu focal and jammy version.
Then ,,, we should not use `pynecone` on ubuntu and close the issue?

**Comment by picklelo** [comment]
Just name your project something else besides `test` (or any other builtin Python package) and it should work.

**Comment by dev-onejun** [comment]
oh, right. I mean don't use the name `test`.
