### ISSUE TITLE
Question: When Is Pynecone Production ready?

### ISSUE THREAD

**Issue by Shahin-rmz** [pynecone-io/pynecone#398]
Hello,
Pynecone aims and solves very important problem of Python devs.
It was a day, that Python devs had *almost* no chance to deliver an app, without doing Javascript.
Then the solutions like `streamlit` and `Dash` came up, which either was not totally free, or does not give the dev enough flexibility.
The came a solution like `pyscript`, which is not ready yet, or at least goes so deep inside front end technology.

Pynecone aims the problem correctly and solves the issue in very nice way. it gives enough flexibilty as well as strong and easy way of delivering app.
My question is that, is it production ready?
I play around and see some apps in Gallery or in the doc does not appear working correctly, or at least do show desired behavior when I click on them **with delay**. does it mean that we should not bring market apps with Pynecone soon?

**Comment by Alek99** [comment]
Pynecone is still pretty new we had our first public release in December 2022. We hope to have Pynecone production ready and stable by sometime in March. In the meantime I still would encourage you to try Pynecone in your stack because it is stable enough for most applications.

We are in the process of optimizing/speed up our framework and fixing bugs as they come up. Our next release should see a major speed improvement in larger apps. This delay you are talking about is coming from our front-end code not being optimized but next release we are adding a feature which should significant speed this up. Stay tuned

**Comment by Shahin-rmz** [comment]
Can't wait to work with Pyencone.
Will begin with my first project with it soon.
Thanks
