### ISSUE TITLE
pc.button on_click event not working on mobile

### ISSUE THREAD

**Issue by ImPandax** [pynecone-io/pynecone#508]
### The problem

Creating a button like `pc.button("text", on_click=MyState.do_something)` triggers the corresponding event on computer but not on mobile.

### Tested devices

- Computer with Firefox | Windows 11
- iPhone/iPad with Safari | iOS 16.3/iPadOS 16.3

### Additional info

The button doesn't trigger your own events from your own state, however `pc.toggle_color_mode` seems to be working when combined with `on_click`.

### Example code

```
import pynecone as pc


class MainState(pc.State):
    drawer_visible: bool = False

    def toggle_drawer(self):
        self.drawer_visible = not self.drawer_visible

    def redirect(self):
        return pc.redirect("/test")


def index():
    return pc.center(
        pc.vstack(
            pc.button(
                pc.icon(tag="HamburgerIcon"),
                on_click=MainState.toggle_drawer,
            ),
            pc.drawer(
                pc.drawer_overlay(
                    pc.drawer_content(
                        pc.drawer_header("MENU"),
                        pc.drawer_body("menu item"),
                        pc.drawer_footer(
                            pc.button(
                                pc.icon(tag="CloseIcon"),
                                on_click=MainState.toggle_drawer,
                            ),
                        ),
                    ),
                ),
                is_open=MainState.drawer_visible,
                placement="top",
            ),
            pc.button("click to redirect", on_click=MainState.redirect),
            pc.button("darkmode", on_click=pc.toggle_color_mode),
        ),
        height="100vh",
    )


app = pc.App(
    state=MainState,
)
app.add_page(
    index,
)
app.compile()
```

**Comment by jiangmiemie** [comment]
![image](https://github.com/pynecone-io/pynecone/assets/69161207/68800bf1-ee35-45f9-9f6a-0d73a2622356)
if use computer with mobile type ,  can work .

**Comment by Alek99** [comment]
This may be a chakra ui problem, I need to investigate more

**Comment by Alek99** [comment]
On my iPhone its working are you on android?

**Comment by jiangmiemie** [comment]
yes ，my phone is android （Xiaomi） with EDG

**Comment by jiangmiemie** [comment]
In order to confirm whether it is a mobile phone problem, I downloaded https://github.com/pynecone-io/pcweb. And changed the Prue python on the homepage to local. In order to eliminate the network reasons, I used the local wifi IP address and port number to link, the result is as shown in the figure

![125b8277fc9debca49f106aefb9ecef](https://github.com/pynecone-io/pynecone/assets/69161207/a96f655f-50ff-4d44-b2b5-b2ceb46e2529)
![d3197f99cda4d69e923b66ad422e37d](https://github.com/pynecone-io/pynecone/assets/69161207/c9989127-0d41-4587-9e55-7d9656e56c51)

My test computer is window11+linux kernel, and the test time is 5/28. I reinstalled pynecone to troubleshoot the version problem. The pynecone version is 0.1.32. At the same time, I downloaded the latest public example on 5/28.

**Comment by jiangmiemie** [comment]
Node is 18.12.1

**Comment by jiangmiemie** [comment]
I found the problem, as stupid as it sounds, the browser's default settings prevent the window from popping up @Alek99

**Comment by picklelo** [comment]
Closing this issue since it seems to be working now. Feel free to re-open if the problem persists.
