### ISSUE TITLE
Fix id auto primary key

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#812]
We currently always assume an primary key named `id` which can cause problems - let's fix this.

**Comment by kasun** [comment]
I did some digging on this and see two possible solutions.

1) Keep the id field definition in `Model` class [1] as it is and if any subclass has defined at-least one primary key drop this id field at class initialisation.

2) Remove the id field definition in `Model` class [1] and add it dynamically only if a sub class has no defined primary key fields.

If there is no objections for the solution 1 I can submit a PR. Solution 2 is harder from what I tested because of how SQLModel infers field types from type annotations.

[1] https://github.com/pynecone-io/pynecone/blob/main/pynecone/model.py#L28

**Comment by picklelo** [comment]
Sorry for the delay here - Option 1 works well I think. We could also remove the `id` completely and require the user to have to declare it explicitly each time to avoid confusion. But I think it's nice to have it in by default - we will just need to document this feature after the PR is merged.

**Comment by kasun** [comment]
Thanks. Submitted a PR for this.
