### ISSUE TITLE
on_click with multiple options doesn't work

### ISSUE THREAD

**Issue by maksp-glitch** [pynecone-io/pynecone#827]
**Describe the bug**
I want to set a var and call a function at the same time, when a radio group has changed. This doesn't work. 
Following error occurs: 
`ValueError: Event handler: <function state.set_selectedSize at 0x107a29580> for uncontrolled event on_click should not take any args.`

**To Reproduce**
 `pc.radio_group(
                        State.sizerunSell,
                        on_change=[State.set_selectedSize],
                        on_click=[State.data_filter, State.set_selectedSize]
                        )
                    )`

**Expected behavior**
To call the function and set the variable. 

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: latest
 - OS: Mac
 - Browser (Optional): Chrome

**Comment by masenf** [comment]
This problem arises because the `on_click` event **does NOT carry a value**, so you can't "set" anything in response to that event. [1]

Further, `on_click` fires _before_ `on_change`, so your `State.data_filter` event handler would get called when `State.selectedSize` still has the previous value.

------------------------

What is the motivation for handling `on_click` for `radio_group` (i.e. what does `data_filter` do in relation to the form)?

If `data_filter` depends on the value of `State.selectedSize`, then I would chain the `data_filter` event handler off of `on_change` by returning it from `set_selectedSize`.

```
on_change -> State.set_selectedSize(value) -> State.data_filter
```


```python
import pynecone as pc


class State(pc.State):
    sizerunSell = ["foo", "bar", "baz"]
    selectedSize = "foo"

    def data_filter(self):
        print(f"data_filter() triggered, selectedSize is {self.selectedSize}")

    def set_selectedSize(self, v: str):
        print(f"set_selectedSize({v}) triggered")
        self.selectedSize = v
        return self.data_filter


def index() -> pc.Component:
    return pc.radio_group(State.sizerunSell, on_change=[State.set_selectedSize])


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

------------------

[1] If you knew the value to set in response to `on_click`at compile time or used `pc.cond`, then you could use a `lambda` to pass a value. `on_click=lambda: State.set_something(42)`.

**Comment by Lendemor** [comment]
The way to handle event handlers has been changed since this issue was opened, I don't think it is relevant anymore.
